### ISSUE TITLE
Roadmap Twitter v2

### ISSUE THREAD

**Issue by boogheta** [python-twitter-tools/twitter#435]
- [X] ensure code compatibility
- [x] add helper class Twitter2
- [x] add helper class TwitterStream2
- [ ] update tests
- [x] handle :id argument in middle of urls (i.e. /2/tweets/id/retweeted_by)
- [x] better document middle arguments use and _id
- [ ] complete internal help doc
- [ ] improve expansions, fields arguments use
- [ ] cleanup _json / params mess
- [ ] Test all open v2 routes https://developer.twitter.com/en/docs/api-reference-index#Twitter
- [ ] complete documentation
- [ ] cleanup shell tools & irc bot ?

[example calls](https://pad.lqdn.fr/p/m%C3%A9dialab-twitter)

**Comment by djotaku** [comment]
Is this meant to support https://developer.twitter.com/en/docs/twitter-api/migrate/whats-new?ref=em-elq-reapply-essential-access&utm_source=elq&utm_medium=em&utm_campaign=developer-account-v2&elqTrackId=BB26307291237E713FDECAF140B9059D ?

And is there a timeline on moving towards it?

Thanks!

**Comment by boogheta** [comment]
Mainly yes. It sill lacks documentation and a few usecases but it is mostly functional in the [api_v2 branch](https://github.com/python-twitter-tools/twitter/tree/api_v2) which is released under the twitter-2.0-alpha release installable with pip via `pip install twitter==2.0a0`
I hope to find the time to complete it during the summer.

**Comment by hugovk** [comment]
We're no longer maintaining this project and will be archiving it.

The existing releases and code will remain available in their current state.
